### PR TITLE
license: 双重许可

### PR DESCRIPTION
**Pull request by undefined-moe**

### CODE REVIEW

**Comment by undefined-moe** [comment]
@Macesuted @junukwon7 @Rratic @BATTLEHAWK00 @Nerlci Request approval

**Comment by undefined-moe** [comment]
Related: https://github.com/hydro-dev/Hydro/discussions/138

**Comment by Macesuted** [comment]
Approved.

**Comment by undefined-moe** [comment]
Or, if you have any suggestion to the license, comments are welcome.

**Comment by Nerlci** [comment]
Approved.

**Comment by Rratic** [comment]
Approved

**Review by wuxianucw — APPROVED** [review]

**Comment by undefined-moe** [comment]
@junukwon7

**Comment by junukwon7** [comment]
Approved

**Pull request merged**
