### PR TITLE
Add mbps limit

### PR DESCRIPTION
**Pull request by StupidQu**
在将评测发送到评测机时检查最大带宽是否能够将数据传输完毕，对小带宽的评测机有帮助。

### CODE REVIEW

**Comment by StupidQu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pandadtdyy** [comment]
1. 你skip了这个点怎么办，这个点就留着卡在队列里吗？
2. 请不要使用`content1` `content2` 这种不规范命名。
3. 一般局限的更多是上传速度而不是下载速度。

更好的方法应该是web上传带宽尽量大或将数据放置于外置s3存储上。

**Comment by StupidQu** [comment]
1. 不会留在评测队列里，会重新加入到 task 中等待下一个评测机获取。
2. 已更改。
3. 这个功能适用情况是评测服务器被限制在一个较低的带宽时，默认web服务器的带宽应该比评测服务器更大。

这个功能在我的机器上工作良好，不会卡在评测队列，感谢您抽空查看。

**Review by undefined-moe — CHANGES_REQUESTED** [review]
Refusing to judge specific problem is absolutely NOT an acceptable solution.

**Comment by StupidQu** [comment]
> Refusing to judge specific problem is absolutely NOT an acceptable solution.

我不太确定我是否正确理解了你的问题，这不是在拒绝评测特定问题，而是将评测的任务交给带宽足够拉取数据的评测机，且如果不设置 mbps，则将不会受到此限制。

**Comment by undefined-moe** [comment]
What if:

- There's only one judge configured and it doesn't met requirements?
- Those testdata already fully or partially cached in the cache directory?

This logic prevents tasks being distributed to specific judge, while that judge may be able to process the task.

**Comment by undefined-moe** [comment]
Commonly, we assume that the judges are deployed in the same region of the file server (or a storage gateway), and are able to download files at a speed of at least 100Mbps.
If you really want to handle low-bandwidth situation, please try to perform some low-priority background testdata sync instead of simply picking judge machines.

**Comment by StupidQu** [comment]
感谢您的回复，我尝试实现这个功能是因为我的评测机与web服务器并不在同一个内网内，且评测机的带宽被限制在一个很低的速度。如果只有一台评测机，那么大可以不设置 mbps，这样就不会被这个限制所拦截。如果尝试在后台同步数据，就会丢失掉按需同步数据的优势。当前Hydro在同步测试数据的时候有 60s 的最大时间限制。

这个功能对有很多评测机，但是评测机的带宽不同的人有作用。无论怎样，感谢您的建议。

**Comment by StupidQu** [comment]
对于您说的第二种情况，如果一道题目可以被同步在一台特定的机器上，那么它在分配评测的时候也将一定能被分配到。

**Comment by undefined-moe** [comment]
I mean, why not create a background sync task for extra-large testdata files when the task received, and after a time period, when the sync task finished, this judge is able to judge this problem.

By the way, 60s download limit (for single file) is only a way to prevent judging queue hung (sometimes its not downloading but the connection's still active). It's welcome if you have better solution.

P.S. Even if you are using ADSL network with a 8Mbps download speed, 60s is enough for you to download a 60MB file.

**Comment by StupidQu** [comment]
> I mean, why not create a background sync task for extra-large testdata files when the task received, and after a time period, when the sync task finished, this judge is able to judge this problem.
> 
> By the way, 60s download limit (for single file) is only a way to prevent judging queue hung (sometimes its not downloading but the connection's still active). It's welcome if you have better solution.
> 
> P.S. Even if you are using ADSL network with a 8Mbps download speed, 60s is enough for you to download a 60MB file.

感谢您的建议，我还有几点不是很明白。

- 当评测任务被评测机接受后，应该在记录页面显示什么？这个评测记录是应该继续被评测还是被取消？
- 是否可以将这个60s的拉取数据时间限制改为一个动态浮动的值，以保证数据确实可以被拉取？

由于我的评测机在中国（大陆），而 web 服务器在香港，拉取数据的时候时常不能够跑满 8Mbps 的速率限制。

**Pull request closed without merging**
