### PR TITLE
OAuth: Better OAuth

### PR DESCRIPTION
**Pull request by air-adteam**
Add platform name recognition fields for the use of multiple OAuth modules.

### CODE REVIEW

**Comment by undefined-moe** [comment]
So what's this new column for?

**Comment by air-adteam** [comment]
> So what's this new column for?

Record the name of the platform. For example, QQ and GitHub make a distinction to pave the way for the later template to show the platform binding.

However, in order to be compatible with early plug-ins, the "platform" here is made an optional attribute, and the plug-ins developed later are recommended to register the platform name (the "platform" field is added to the operation to mark the platform name)

**Comment by undefined-moe** [comment]
Then implement it. Don't do things by half.

**Comment by air-adteam** [comment]
> Then implement it. Don't do things by half.

Yes, there is a three-step plan here: 1. Update the API within Hydrooj. 2. Update the template. 3. Update other official plugins. Currently, the API section has been updated, and I believe that changing these should be the first step completed.

**Comment by undefined-moe** [comment]
There's no breaking change so no need to do it step by step. It can be implemented altogether.

**Pull request closed without merging**
