### PR TITLE
core: fix permission check for deleting discussion replies

### PR DESCRIPTION
**Pull request by Lyricus233**
修复删除回复时权限检查问题。

### CODE REVIEW

**Comment by Lyricus233** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pandadtdyy** [comment]
贴主没有权利删楼中楼。

**Comment by Lyricus233** [comment]
In order to delete a reply, one should have the 'PERM_DELETE_DISCUSSION_REPLY_SELF' permission (?)

**Comment by pandadtdyy** [comment]
fix in [`f85e254`](https://github.com/hydro-dev/Hydro/pull/635/commits/f85e254d81f89666e1f6c2285642d82392eed9ec).

**Pull request closed without merging**
